object FrmConsVentas: TFrmConsVentas
  Left = 0
  Top = 0
  BorderIcons = []
  BorderStyle = bsNone
  Caption = 'ConsVentas'
  ClientHeight = 680
  ClientWidth = 800
  Color = clBtnFace
  DefaultMonitor = dmMainForm
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poOwnerFormCenter
  Visible = True
  WindowState = wsMaximized
  OnClose = FormClose
  PixelsPerInch = 96
  TextHeight = 13
  object pageConsVentas: TcxPageControl
    Left = 0
    Top = 0
    Width = 800
    Height = 680
    Align = alClient
    ParentShowHint = False
    ShowHint = True
    TabOrder = 0
    Properties.ActivePage = TabConsVentas
    Properties.CloseButtonMode = cbmActiveTab
    Properties.CustomButtons.Buttons = <>
    Properties.Options = [pcoAlwaysShowGoDialogButton, pcoGradient, pcoGradientClientArea, pcoRedrawOnResize, pcoUsePageColorForTab]
    Properties.TabSlants.Kind = skCutCorner
    Properties.TabSlants.Positions = [spRight]
    LookAndFeel.Kind = lfUltraFlat
    LookAndFeel.NativeStyle = False
    LookAndFeel.SkinName = 'Caramel'
    TabSlants.Kind = skCutCorner
    TabSlants.Positions = [spRight]
    OnCanCloseEx = pageConsVentasCanCloseEx
    ClientRectBottom = 673
    ClientRectLeft = 4
    ClientRectRight = 793
    ClientRectTop = 28
    object TabConsVentas: TcxTabSheet
      Caption = 'Cons Ventas'
      ImageIndex = 0
      object BtnVentasXDia: TcxButton
        Left = 41
        Top = 60
        Width = 136
        Height = 85
        Hint = 'Ventas por D'#237'a'
        ParentCustomHint = False
        BiDiMode = bdLeftToRight
        Caption = 'Ventas X D'#237'a'
        LookAndFeel.Kind = lfOffice11
        LookAndFeel.NativeStyle = False
        LookAndFeel.SkinName = 'LondonLiquidSky'
        OptionsImage.ImageIndex = 14
        OptionsImage.Images = DmGlobal.ImlBotones
        OptionsImage.Layout = blGlyphTop
        ParentBiDiMode = False
        ParentShowHint = False
        PopupAlignment = paRight
        ShowHint = True
        TabOrder = 0
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        OnClick = BtnVentasXDiaClick
      end
      object BtnVentasXMarca: TcxButton
        Left = 225
        Top = 60
        Width = 136
        Height = 85
        Hint = 'Ventas por Marca'
        ParentCustomHint = False
        BiDiMode = bdLeftToRight
        Caption = 'Ventas X Marca'
        LookAndFeel.Kind = lfOffice11
        LookAndFeel.NativeStyle = False
        LookAndFeel.SkinName = 'LondonLiquidSky'
        OptionsImage.ImageIndex = 15
        OptionsImage.Images = DmGlobal.ImlBotones
        OptionsImage.Layout = blGlyphTop
        ParentBiDiMode = False
        ParentShowHint = False
        PopupAlignment = paRight
        ShowHint = True
        TabOrder = 1
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        OnClick = BtnVentasXMarcaClick
      end
      object BtnOrdenesXFinal: TcxButton
        Left = 409
        Top = 60
        Width = 136
        Height = 85
        Hint = 'Ordenes por Finalizar'
        ParentCustomHint = False
        BiDiMode = bdLeftToRight
        Caption = 'Ordenes X Finalizar'
        LookAndFeel.Kind = lfOffice11
        LookAndFeel.NativeStyle = False
        LookAndFeel.SkinName = 'LondonLiquidSky'
        OptionsImage.ImageIndex = 16
        OptionsImage.Images = DmGlobal.ImlBotones
        OptionsImage.Layout = blGlyphTop
        ParentBiDiMode = False
        ParentShowHint = False
        PopupAlignment = paRight
        ShowHint = True
        TabOrder = 2
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        OnClick = BtnOrdenesXFinalClick
      end
      object BtnMasVendidos: TcxButton
        Left = 593
        Top = 60
        Width = 136
        Height = 85
        Hint = 'Productos m'#225's Vendidos'
        ParentCustomHint = False
        BiDiMode = bdLeftToRight
        Caption = 'Productos m'#225's Vendidos'
        LookAndFeel.Kind = lfOffice11
        LookAndFeel.NativeStyle = False
        LookAndFeel.SkinName = 'LondonLiquidSky'
        OptionsImage.ImageIndex = 17
        OptionsImage.Images = DmGlobal.ImlBotones
        OptionsImage.Layout = blGlyphTop
        ParentBiDiMode = False
        ParentShowHint = False
        PopupAlignment = paRight
        ShowHint = True
        TabOrder = 3
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        OnClick = BtnMasVendidosClick
      end
    end
  end
end
